### ISSUE TITLE
Problem with version_string

### ISSUE THREAD

**Issue by animetrom** [mt-mods/beowulf#21]
First of all, I apologize for the inconvenience regarding this, as I am a bit of a layman in some things.
I would like to know how I can make Minetest detect the version the user is using, since I installed the mod and ran it and it didn't work.
I know there is the strict_protocol_version_checking = true line for minetest.conf, but this restricts any older version of minetest.
Can you please help me?

**Comment by wsor4035** [comment]
you need to remove https://github.com/minetest/minetest/blob/56123b2fbe1ad4e7878556f8d51c551d84fb92e7/src/script/lua_api/l_server.cpp#L257 and https://github.com/minetest/minetest/blob/56123b2fbe1ad4e7878556f8d51c551d84fb92e7/src/script/lua_api/l_server.cpp#L281 and compile
