### ISSUE TITLE
I want to log always all msg inside logging.lua to own log file

### ISSUE THREAD

**Issue by Festus1965** [mt-mods/beowulf#5]
how ?

reason:
proof where most of the gamer come, get better imagine about source apps / clients:

as beside:
39 - 3 - 5.2.0 - 28 (some of my kids 5.2.0)
39 - 4 - 5.4.1 - 28 (myself 5.4.1)
I see
39 - 4 - 2.0.0 - 28 (MultiCraft Client ? - didn't test)
also
32 - 1 - 1.1.3 - 28

so as of your excellent help to see how we mt loose gamer, and how other server rise, that could help with facts where the gamer (using client) come from ,
identify
and maybe solve our (mt server) problems loosing gamer.

For me would be ok, one line that every detected msg is getting into an own beowulf.log

**Comment by BuckarooBanzay** [comment]
You can filter the regular debug output from `debug.txt` and extract the beowulf stuff with this:
```bash
grep beowulf debug.txt
```
There should be no need for another logging facility besides the default one

**Comment by Festus1965** [comment]
nice to know,
under MultiCraft2 there is no debug.txt
or the settings of allow or report are different.

would have been nice, as watching the reports on a own programmed beerchat channel offers some more knowledge what 2 other apps are used most,
and that there are two main corrections from the server:
* one seam to offer more then the 8 slots (tried to access hotbar out off ... item=8 )
* tried to access from higher distance
* also most the version 2.0.0 comes in with playerxxx (x=1-9) and sure not robots
